### ISSUE TITLE
Broken pipeline after a few miniutes

### ISSUE THREAD

**Issue by vidyli** [artemrys/scrapy-rabbitmq-publisher#1]
```
021-01-21 14:03:19 [pika.adapters.utils.io_services_utils] ERROR: _AsyncBaseTransport._produce() failed, aborting connection: error=BrokenPipeError(32, 'Broken pipe'); sock=<socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60235)>; Caller's stack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 819, in _produce
    num_bytes_sent = self._sigint_safe_send(self._sock,
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 819, in _produce
    num_bytes_sent = self._sigint_safe_send(self._sock,
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-01-21 14:03:19 [pika.adapters.utils.io_services_utils] INFO: _AsyncTransportBase._initate_abort():
```

**Comment by artemrys** [comment]
Sorry, I missed your issue. Do you still observe this behaviour?
