### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by guishake** [artemrys/scrapy-rabbitmq-publisher#3]
Hello,

when starting the pipeline, I get this error 
```sh
Traceback (most recent call last):
  File "xxx/py39/lib/python3.9/site-packages/twisted/internet/defer.py", line 962, in __del__
    log.failure(format,
  File "xxx/py39/lib/python3.9/site-packages/twisted/logger/_logger.py", line 190, in failure
    self.emit(level, format, log_failure=failure, **kwargs)
  File "xxx/py39/lib/python3.9/site-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/xxx/py39/lib/python3.9/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "xxx/py39/lib/python3.9/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "xxx/py39/lib/python3.9/site-packages/twisted/python/log.py", line 595, in emit
    _publishNew(self._newObserver, eventDict, textFromEventDict)
  File "xxx/py39/lib/python3.9/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
    observer(eventDict)
  File "xxx/py39/lib/python3.9/site-packages/twisted/logger/_stdlib.py", line 115, in __call__
    self.logger.log(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
builtins.TypeError: _findCaller() takes from 1 to 2 positional arguments but 3 were given

```

isn't it compatible with py 39 ?

**Comment by guishake** [comment]
was an issue with the settings !
